blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('posts.urls',namespace='posts')),
    path("api-auth",include("rest_framework.urls")),
]

posts/urls.py
from django.urls import path
from .views import post_list, post_detail, PostListView,post_share,post_comment

app_name = "posts"

urlpatterns = [
    path("", post_list, name="post_list"),
    path('tag/<slug:tag_slug>/',post_list,name='post_list_by_tag'),
    # path("", PostListView.as_view(), name="post_list"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", post_detail, name="post_detail"),
    path('<int:post_id>/share/',post_share,name='post_share'),
    path('<int:post_id>/comment/',post_comment,name='post_comment'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    name = models.CharField(null=True,blank=True,max_length=100)

posts/models/comments.py
from django.db import models
from ..models import Post


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

posts/models/posts.py
from django.conf import settings
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


User = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=Status.choices, default=Status.DRAFT
    )
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [models.Index(fields=["-publish"])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # print(self.args,self.kwargs)
        return reverse(
            "posts:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ("name",)

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

posts/forms/comments_form.py
from django import forms
from ..models import Comment



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','body']

posts/forms/email_post_form.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25) 
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)
    
       

posts/views.py
from django.shortcuts import render, get_object_or_404

from posts.forms import EmailPostForm, CommentForm
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.http import Http404
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    comment_data = request.POST
    form = CommentForm(data=comment_data)
    if form.is_valid():
        # create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the port to the comment
        comment.post = post
        # save the comment to the database
        comment.save()
    return render(
        request, "posts/comment.html", {"post": post, "comment": comment, "form": form}
    )


class PostListView(ListView):
    """Alternative post list view """

    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3
    template_name = "posts/list.html"


from django.core.mail import send_mail


def post_share(request, post_id):
    # retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == "POST":
        # Form was submitted
        aa = {}
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # form fields passed validation
            cd = form.cleaned_data
            print("aa", aa)
            print("cd", cd)
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read" f"{post.title}"
            message = (
                f"Read{post.title} as {post_url}\n\n"
                f"{cd['name']}\\'s comments: {cd['comments']}"
            )
            send_mail(subject, message, "zunayeduapcse@gmail.com", [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()
        # print(form)

    return render(
        request, "posts/share.html", {"post": post, "form": form, "sent": sent}
    )


def post_list(request, tag_slug=None):
    print("tag_slug", tag_slug)
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

        print(post_list)
    # pagination with 3 posts per page
    paginator = Paginator(post_list, 3)  # 3 posts in each page
    page_number = request.GET.get("page", 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        # if page_number is not on integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, "posts/list.html", {"posts": posts, "tag": tag})


def post_detail(request, year, month, day, post):
    try:
        post = get_object_or_404(
            Post,
            status=Post.Status.PUBLISHED,
            slug=post,
            publish__year=year,
            publish__month=month,
            publish__day=day,
        )
        # List of active comments for this post
        comments = post.comments.filter(active=True)
        # Form for users to comments
        form = CommentForm()

        # List of similar posts
        post_tags_ids = post.tags.values_list("id", flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
            id=post.id
        )
        similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
            "-same_tags", "-publish"
        )[:4]
    except Post.DoesNotExist:
        raise Http404("No Post found")
    return render(
        request,
        "posts/detail.html",
        {
            "post": post,
            "comments": comments,
            "form": form,
            "similar_posts": similar_posts,
        },
    )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Dynamic Title Area  -->
    <title>{% block title %} {% endblock %}</title>

    <link href={% static "posts/style.css" %} type="text/css" rel="stylesheet" >
  </head>
  <body>
    
    <div id="content">
      {% block content %}

      

      <!-- Dynamic Content area -->

      {% endblock %}
    </div>

    <div id="sidebar">
      <h2>My Blog</h2>
      <p>This is my Blog.</p>
    </div>
  </body>
</html>

templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{page.previous_page_number}}">Previous</a>
    {%endif%}

    <span class="current">
      Page {{page.number}} of {{page.paginator.num_pages}}
    </span>
    {% if page.has_next %}
    <a href="?page={{page.next_page_number}}">Next</a>
    {%endif%}
  </span>
</div>

templates/posts/comment.html
{% extends 'base.html'%}




{%block title %} Add a Comment {%endblock%}


{% block content %}

{% if comment%}
    <h2>Your Comment has been added.</h2>
    <p><a href="{{post.get_absolute_url}}">Back to the post</a></p>
{% else %}

    {% include "../posts/includes/comment_form.html" %}

    {% endif %}


{% endblock%}

templates/posts/detail.html
{% extends "base.html" %}

{% block title %}

{{post.title}}

{% endblock %}

{% block content %}

<h1>{{post.title}}</h1>

<p class="date">
    Published {{post.publish}} by {{post.author}}
</p>

{{post.body | linebreaks}}

<p >
    <a href="{% url "posts:post_share" post.id %}">
        Share this post
    </a>
</p>


<h2>Similar posts</h2>

{% for post in similar_posts %}
<p>
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
</p>
{% empty %}
There are no similar posts yet.
{%endfor%}


<p><a href="{% url "posts:post_list" %}">Back to Home</a></p>

{% with comments.count as total_comments %}
    <h2>
        {{total_comments}} comment {{total_comments|pluralize}}
    </h2>
{% endwith %}

{% for comment in comments%}

    <div class="comment">
        <p class="info">
            Comment {{forloop.counter}} by {{comment.name}}
            {{comment.created}}
        </p>
        {{comment.body|linebreaks}}
    </div>
    {% empty %}
    <p>There are no comments.</p>
    {%endfor%}
    {% include "../posts/includes/comment_form.html" %}

    
{% endblock %}

templates/posts/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "posts:post_comment" post.id %}" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <p><input type="submit" value="Add Comment"></p>
</form>

templates/posts/list.html
{% extends "base.html" %}

<!-- Block Title -->

{%block title%} My Blog {%endblock%}

<!-- Block Content -->

{% block content%}

<h1>My Blog</h1>
{% if tag%}
  <h2>Posts tagged with "{{tag.name}}"</h2>
{% endif%}

{% for post in posts %}
<h2>
  <a href="{{post.get_absolute_url}}">{{post.title}}</a>
</h2>

<p class="tags">Tags: 
{% for tag in post.tags.all%} 
  <a href="{% url "posts:post_list_by_tag" tag.slug %}">
    {{tag.name}}
  </a>
  {% if not forloop.last %}, {%endif%}
  {%endfor%}
  <!-- {{post.tags.all|join:","}} -->
</p>

<p class="date">Published {{ post.publish }} by {{post.author}}</p>

{{post.body|truncatewords:30|linebreaks}} 

{%endfor%} 
{% include "pagination.html" with page=posts %} {% endblock %}

templates/posts/post.html
{% extends 'base.html'%}


{% block title %}

Share a post

{% endblock%}


{% block content%}

{% if sent %}

    <h1>E-mail Successfully sent</h1>
    <p>"{{post.title}}" was Successfully sent to {{form.cleaned_data.to}}</p>

{% else %}

<h1>Share "{{post.title}}" by email</h1>


{%endblock%}

templates/posts/share.html
{% extends 'base.html' %}

{% block title %} Share Post {%endblock%}


{% block content%}

<h1>{{post}}</h1>

{%if sent %}

<h1>e-mail sent Successfully</h1>

<p class="button"><a href="{% url "posts:post_list" %}">Back to Home</a></p>

{%else %}
<p><a href="{% url "posts:post_list" %}">Back to Home</a></p>
    <form method="post">
        <!-- {%for field in form%}

            <div>
                {{field.erros}}
                {{field.label_tag}} {{field}}
            </div>

        {%endfor%} -->

        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Send e-mail">
    </form>


{%endif%}
{%endblock%}